// <auto-generated />
namespace CarRental.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change_table_name_AdditionalEquipments_to_Equipments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_table_name_AdditionalEquipments_to_Equipments));
        
        string IMigrationMetadata.Id
        {
            get { return "201703152025207_Change_table_name_AdditionalEquipments_to_Equipments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
