// <auto-generated />
namespace CarRental.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Create_image_entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_image_entity));
        
        string IMigrationMetadata.Id
        {
            get { return "201703051150238_Create_image_entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
