// <auto-generated />
namespace CarRental.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_vehicle_type_entity_and_connection_changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_vehicle_type_entity_and_connection_changes));
        
        string IMigrationMetadata.Id
        {
            get { return "201702261933213_Add_vehicle_type_entity_and_connection_changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
