// <auto-generated />
namespace CarRental.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_user_to_reservation_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_user_to_reservation_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201703211857552_Add_user_to_reservation_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
