// <auto-generated />
namespace CarRental.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Fix_relation_vehicle_with_image : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fix_relation_vehicle_with_image));
        
        string IMigrationMetadata.Id
        {
            get { return "201703051334595_Fix_relation_vehicle_with_image"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
